#!/bin/bash

foreground="e5dcd6"
background="131313"

## Normal/regular colors (color palette 0-7)
regular0="272d70"  # dark blue
regular1="cd0000"  # red
regular2="317256"  # green
regular3="a57d00"  # yellow
regular4="ae5000"  # orange
regular5="934c93"  # purple
regular6="204c7f"  # cyan
regular7="e5dcd6"  # white

## Bright colors (color palette 8-15)
bright0="204c7f"   # bright blue
bright1="dc4c4c"   # bright red
bright2="49ab81"   # bright green
bright3="e5b513"   # bright yellow
bright4="f97300"   # bright orange
bright5="a86fa8"   # bright purple
bright6="00baba"   # bright cyan
bright7="ffffff"   # bright white

## Misc colors
selectionforeground="fff5ee"
selectionbackground="474444"
